<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Door extends Model
{
    protected $guarded=[];
    public function images(){
        return $this->hasMany(Image::class,'door_id');
    }
    public function aluminum_type(){
        return $this->belongsTo(AluminumType::class,'aluminum_type_id');
    }
    public function wood_type(){
        return $this->belongsTo(AluminumType::class,'wood_type_id');
    }
    public function category(){
        return $this->belongsTo(Category::class,'category_id');
    }
    public function delete()
    {
        $this->images()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
